// data.js - Automatically generated by SnapBlitz Admin Panel

window.SITE_DATA = {
    "siteTitle": "Snap Blitz",
    "profileUrl": "https://www.instagram.com/snap_blitz",
    "defaultButtonText": "Get Link",
    "maxResults": 50,
    "socialMedia": {
        "instagram": "https://www.instagram.com/snap_blitz",
        "facebook": "https://www.facebook.com/snapblitz",
        "linkedin": "https://www.linkedin.com/in/snapblitz",
        "youtube": "https://www.youtube.com/@snapblitz",
        "telegram": "https://t.me/snapblitz"
    },
    "theme": {
        "backgroundPrimary": "#000000ff",
        "accentPrimary": "#8b5cf6",
        "accentSecondary": "#7c3aed"
    },
    "links": [
        {
            "id": "premiere-pro",
            "title": "Premiere Pro",
            "description": "Professional video editing software for creators",
            "keywords": [
                "premiere",
                "video editor",
                "adobe",
                "editing"
            ],
            "thumbnail": "Assets/Links thumbnail/premiere.webp",
            "buttonText": "Download",
            "ctaText": "Follow @snap_blitz to download Premiere Pro",
            "followRedirectUrl": "https://example.com/premiere",
            "priority": 1,
            "visible": true
        },
        {
            "id": "after-effects",
            "title": "After Effects",
            "description": "Motion graphics and visual effects software",
            "keywords": [
                "after effects",
                "vfx",
                "animation",
                "adobe"
            ],
            "thumbnail": "Assets/Links thumbnail/aftereffects.webp",
            "buttonText": "Download",
            "ctaText": "Follow @snap_blitz to download After Effects",
            "followRedirectUrl": "https://example.com/ae",
            "priority": 2,
            "visible": true
        },
        {
            "id": "capcut",
            "title": "CapCut Pro",
            "description": "Mobile video editor with AI features",
            "keywords": [
                "capcut",
                "mobile",
                "video editor",
                "reels"
            ],
            "thumbnail": "Assets/Links thumbnail/capcut.webp",
            "buttonText": "Get App",
            "ctaText": "Follow @snap_blitz for CapCut Pro",
            "followRedirectUrl": "https://example.com/capcut",
            "priority": 3,
            "visible": true
        },
        {
            "id": "Anime",
            "title": "Hianime",
            "description": "my personal favorite free anime watching website",
            "keywords": [
                "anime",
                "free anime",
                "watch anime",
                "OTT"
            ],
            "thumbnail": "Assets/Links thumbnail/hianime.webp",
            "buttonText": "go to website",
            "ctaText": "Follow @snap_blitz for tips",
            "followRedirectUrl": "https://hianime.tv",
            "priority": 4,
            "visible": true
        },
        {
            "id": "Red Dead Redemption 1",
            "title": "Red Dead Redemption 1",
            "description": "RDR 1 for Android device",
            "keywords": [
                "RDR",
                "Red Dead Redemption 1 Android game",
                "Red Dead Redemption game",
                "free game"
            ],
            "thumbnail": "Assets/Links thumbnail/Red Dead Redemption 1.webp",
            "buttonText": "Download",
            "ctaText": "Follow @snap_blitz for free games link",
            "followRedirectUrl": "https://t.me/snap_blitz",
            "priority": 5,
            "visible": true
        },
        {
            "id": "Alight Motion",
            "title": "Alight Motion Pro",
            "description": " best motion graphics editing tool in mobile",
            "keywords": [
                "free Alight Motion",
                "editing",
                "tools",
                "video editing App"
            ],
            "thumbnail": "Assets/Links thumbnail/alight motion.webp",
            "buttonText": "Download",
            "ctaText": "Follow @snap_blitz for free resources",
            "followRedirectUrl": "https://t.me/snap_blitz/438",
            "priority": 6,
            "visible": true
        },
        {
            "id": "viral-reels-prompt",
            "type": "prompt",
            "title": "Viral Reel Prompt",
            "description": "AI prompt for viral Instagram reels",
            "keywords": [
                "chatgpt",
                "prompt",
                "instagram"
            ],
            "thumbnail": "Assets/Links thumbnail/ChatGPT prompt Adithyan M.webp",
            "buttonText": "Get Prompt",
            "ctaText": "Follow @snap_blitz to unlock this AI prompt",
            "promptText": "Act as an expert social media strategist and content creator specializing in Instagram Reels. Your task is to generate 10 highly engaging and viral reel concepts tailored for a tech content creator.\n\nFirst, analyze the current trending audio tracks and formats within the tech niche (e.g., fast-paced unboxings, 'day in the life' vlogs, hidden features tutorials). For each concept, provide a catchy hook for the first 3 seconds to maximize viewer retention.\n\nNext, write a detailed script or shot list for each idea. Specify the exact camera angles (e.g., top-down for desk setups, close-up for product textures) and lighting suggestions (e.g., neon cyberpunk lighting, clean minimal daylight).\n\nThen, outline the caption for each reel. Include SEO-optimized keywords seamlessly integrated into the text, along with a strong Call-To-Action (CTA) encouraging viewers to save the video or comment a specific keyword for an auto-DM link.\n\nFinally, suggest a list of 5-7 targeted hashtags for each concept that balance broad reach with niche engagement, ensuring the content is pushed to the explore page of tech enthusiasts and gadget lovers.",
            "priority": 7,
            "visible": true
        },
        {
            "id": "67Movie website",
            "title": "67movies",
            "description": " free website for watching movies and series open this website on brave browser for ad free experience",
            "keywords": [
                "67Movie",
                "movies",
                "Free",
                "series"
            ],
            "thumbnail": "Assets/Links thumbnail/67Moviewebsite.webp",
            "buttonText": " go to site",
            "ctaText": "Follow @snap_blitz to get the website",
            "followRedirectUrl": "https://67movies.net",
            "priority": 8,
            "visible": true
        },
        {
            "id": "zzzzzzz",
            "title": "zzzzzzz",
            "description": "zzzzzzzz",
            "keywords": [
                "zzzzz"
            ],
            "thumbnail": "",
            "buttonText": "",
            "ctaText": "",
            "visible": false,
            "type": "embed",
            "embedTitle": "zzzzzzzz",
            "youtubeEmbedUrl": "https://www.youtube.com/watch?v=eHTXQW58WhA",
            "actionButtons": [
                {
                    "text": "zzz",
                    "url": "https://www.youtube.com/watch?v=eHTXQW58WhA"
                }
            ],
            "priority": 9
        },
        {
            "id": "Mark Auto Screenshot deleter",
            "title": "Mark Auto Screenshot deleter",
            "description": "useful application for Android delete your screenshot after a certain time automatically",
            "keywords": [
                "Mark Auto Screenshot deleter",
                "Mark",
                "useful app",
                "App"
            ],
            "thumbnail": "Assets/Links thumbnail/Mark Auto Screenshot deleter.webp",
            "buttonText": "Download",
            "ctaText": "Follow @snap_blitz to download Mark Auto Screenshot deleter",
            "followRedirectUrl": "https://play.google.com/store/apps/details?id=com.markOne.ss_app&hl=en_IN",
            "priority": 10,
            "visible": true
        },
        {
            "id": "HyperLock Screen & AOD",
            "title": "HyperLock Screen & AOD",
            "description": " best application for customizing your Android mobile phone hyperos lock screen in any Android mobile phone for completely free",
            "keywords": [
                "HyperLock Screen & AOD",
                "HyperLock Screen",
                "HyperLock",
                "App"
            ],
            "thumbnail": "Assets/Links thumbnail/HyperLock Screen & AOD.webp",
            "buttonText": "Download",
            "ctaText": "Follow @snap_blitz to download HyperLock Screen & AOD",
            "followRedirectUrl": "https://play.google.com/store/apps/details?id=com.appiolab.hyperlockscreenos&hl=en_IN",
            "priority": 11,
            "visible": true
        },
        {
            "id": "moovie",
            "title": "moovie",
            "description": " free website for watching movies and series for completely free Android iOS computer",
            "keywords": [
                "moovie",
                "free movies",
                "movies",
                "website"
            ],
            "thumbnail": "Assets/Links thumbnail/moovie.fun.webp",
            "buttonText": " go to website",
            "ctaText": "Follow @snap_blitz for more content",
            "followRedirectUrl": "https://moovie.fun/",
            "priority": 12,
            "visible": true
        },
        {
            "id": "cineby",
            "title": "cineby",
            "description": " free website for watching movies and series for completely free",
            "keywords": [
                "cineby",
                "free movies",
                "movies",
                "website"
            ],
            "thumbnail": "Assets/Links thumbnail/cineby.at.webp",
            "buttonText": " go to website",
            "ctaText": "Follow @snap_blitz for more content",
            "followRedirectUrl": "https://www.cineby.at/",
            "priority": 13,
            "visible": true
        },
    ]
};
